import {check,captureBrowserEvidence,writeBrowserReport} from '../helpers/browserEvidence.mjs';
const role=(t,k,n)=>t.playwright.getByRole(k,{name:n,exact:true});const wait=l=>l.waitFor({state:'visible',timeoutMs:15000});
/** Run only after normal UI import creates the explicitly owned fictional copy. Caller deletes it. */
export async function runImportedEditor({tab,target,evidenceDir,ownedImportConfirmed}) {
 check(target.verified&&target.environment==='local'&&ownedImportConfirmed,'Verified local target and owned import required');
 check(await role(tab,'textbox','Deck name').evaluate(el=>el.value)==='M7 Atomic Import','Only the named disposable import may be changed');
 const report={schema:1,kind:'browser',environment:'local',sourceRevision:target.sourceRevision,sourceFingerprint:target.sourceTreeFingerprint,method:'CUA live UI; real local API; caller-created fictional Guest import',scenarios:[],evidence:[],acceptance:'Automated only; Kyle acceptance separate',cleanup:{applicationRecords:'Caller must delete this exact owned import; preexisting inventory unchanged'}};
 const capture=async n=>{const e=await captureBrowserEvidence(tab,evidenceDir,n);e.url=e.url.replace(/guest_[A-Za-z0-9_]+/g,'[owned local fixture]');report.evidence.push(e);};const done=id=>report.scenarios.push({id,status:'passed'});
 try {
  await wait(role(tab,'button','View Sword and Shield').nth(0));await wait(tab.playwright.getByText('8 cards',{exact:true}));await wait(tab.playwright.locator('[title="Icon total — Combat: 5"]'));await capture('atomic-import-complete');done('atomic-import-complete-visible-cards-metrics');
  await role(tab,'button','View Sword and Shield').nth(0).click();await wait(role(tab,'dialog','Sword and Shield details'));await role(tab,'button','Pre-Placed').click();await role(tab,'button','Close panel').click();await wait(tab.playwright.getByText('7 cards',{exact:true}));await wait(tab.playwright.locator('[title="Icon total — Combat: 5"]'));await wait(role(tab,'button','Save').and(tab.playwright.locator(':enabled')));await role(tab,'button','Save').click();await wait(role(tab,'button','Saved'));await tab.reload();await wait(tab.playwright.getByText('7 cards',{exact:true}));await wait(role(tab,'button','View Sword and Shield').nth(0));await capture('server-preplacement-save-reload');done('server-preplacement-count-icons-save-reload');
  await role(tab,'button','View Sword and Shield').nth(0).click();await role(tab,'button','Pre-Placed').click();await role(tab,'button','Close panel').click();await wait(tab.playwright.getByText('8 cards',{exact:true}));
  await role(tab,'button','KO character: Lancelot').click();await wait(tab.playwright.locator('[title="Character max — Combat: 0"]'));check(await tab.playwright.locator('.deck-editor__card--ko-dimmed').count()>0,'KO did not dim server-classified cards');check(await tab.playwright.getByText('8 cards',{exact:true}).count()===1,'KO changed physical playable total');await capture('server-ko-dimming');await role(tab,'button','Un-KO character: Lancelot').click();await wait(tab.playwright.getByText('8 cards',{exact:true}));done('server-ko-dimming-and-restore');
  await role(tab,'button','Remove 5 - Combat').nth(0).click();await role(tab,'button','Remove 5 - Combat').nth(0).click();await wait(tab.playwright.getByText('6 cards',{exact:true}));await wait(tab.playwright.locator('[title="Icon total — Combat: 3"]'));await capture('rapid-edits-fresh-metrics');done('rapid-unsaved-edits-fresh-metrics');
  await role(tab,'button','Add Cards').click();await wait(role(tab,'dialog','Add cards'));await capture('server-candidate-panel');await role(tab,'button','Close panel').click();done('server-add-cards-candidates-available');
  await role(tab,'button','Save').and(tab.playwright.locator(':enabled')).click();await wait(role(tab,'button','Saved'));check(!await role(tab,'button','Draw Hand').isEnabled(),'Six-card draft incorrectly allows an eight-card draw');await role(tab,'button','Export').click();await role(tab,'button','JSON').click();await wait(role(tab,'button','Copy to clipboard').and(tab.playwright.locator(':enabled')));const exported=JSON.parse(await role(tab,'dialog','Export deck JSON').locator('pre').textContent());check(exported.total_cards===6&&exported.cards.power_cards.length===3,'Export did not use current saved cards');await capture('edited-server-export');await role(tab,'button','Close panel').click();done('edited-save-server-draw-capability-export');
 }catch(error){report.scenarios.push({id:'imported-editor',status:'failed',reason:String(error).replace(/guest_[A-Za-z0-9_]+/g,'[owned local fixture]')});try{await capture('failure');}catch{}}
 report.browserErrorCount=(await tab.dev.logs({levels:['error'],limit:20})).length;report.counts={passed:report.scenarios.filter(s=>s.status==='passed').length,failed:report.scenarios.filter(s=>s.status==='failed').length,blocked:Math.max(0,6-report.scenarios.filter(s=>s.status==='passed').length),skipped:0};report.status=report.counts.failed===0&&report.counts.passed===6&&report.browserErrorCount===0?'passed':'needs review';report.reportPath=await writeBrowserReport(evidenceDir,report);return report;
}
