import {captureBrowserEvidence,check,writeBrowserReport} from '../helpers/browserEvidence.mjs';
export async function runUnsavedHostCase(tab,{target,evidenceDir,mobile=false}){
 check(target?.verified && target.environment==='local' && target.frontendSource?.revision,'Verified local target required');
 const origin=new URL(target.frontendUrl).origin;check(new URL(await tab.url()).origin===origin,'Wrong local origin');
 const role=(kind,name)=>tab.playwright.getByRole(kind,{name,exact:true}); const wait=l=>l.waitFor({state:'visible',timeoutMs:15000});
 const cases=[];const report={schema:1,environment:'local',kind:'browser',sourceRevision:target.frontendSource.revision,backendRevision:target.health.revision,viewport:mobile?'390x844':'1280x720',theme:'fixed dark',method:'CUA live UI with real local Guest fixture; delayed save explicitly injected by existing host fixture',scenarios:cases,target,evidence:[],cleanup:'Caller privately tracks/removes only created copies; readonly source and existing decks unchanged',acceptance:'Automated only; Kyle approval separate',gaps:['Browser reload/tab close/popstate are host responsibilities and unverified','Native route fixture remains readonly','Account saves/full CSS remain open']};
 const capture=async name=>report.evidence.push(await captureBrowserEvidence(tab,evidenceDir,name));
 try{
  report.viewport=await tab.playwright.evaluate(()=>({width:document.documentElement.clientWidth,height:document.documentElement.clientHeight}));check(report.viewport.width===(mobile?390:1280)&&report.viewport.height===(mobile?844:720),'Actual viewport differs from selected dimensions');
  await wait(role('heading','Independent module harness'));check((await tab.playwright.domSnapshot()).includes('Host identity: Guest'),'Guest required');
  await role('checkbox','Read-only deck').check();await role('combobox','Save fixture mode').selectOption('api');
  await role('textbox','Local deck ID').fill('b4ec3a04-ab17-4a33-b813-df35f8195d75');await role('button','Deck Builder module').click();await wait(role('button','Export'));
  await role('checkbox','Use host unsaved policy').check();await role('checkbox','Read-only deck').uncheck();const input=role('textbox','Deck name');await wait(input);
  const prompt=role('dialog','Unsaved deck changes');const stay=role('button','Stay');const discard=role('button','Discard and continue');const name=`M6 Unsaved ${mobile?'Mobile':'Desktop'}`;
  await input.fill(`${name} draft`);await role('button','Collection module').click();await wait(prompt);check(await input.isVisible(),'Editor unmounted before consent');await capture('guarded-leave');await stay.click();await prompt.waitFor({state:'hidden',timeoutMs:15000});check(await input.evaluate(el=>el.value)===`${name} draft`,'Stay lost draft');
  await role('button','Collection module').click();await wait(prompt);await prompt.press('Escape');await prompt.waitFor({state:'hidden',timeoutMs:15000});check(await input.evaluate(el=>el.value)===`${name} draft`,'Escape lost draft');
  await role('button','Collection module').click();await wait(prompt);await discard.click();await wait(role('heading','My Collection'));await role('button','Deck Builder module').click();await wait(input);check(await input.evaluate(el=>el.value)==='Milestone 3 Local Fixture','Discard failed to recover persisted deck');cases.push({id:'stay-escape-discard-remount',status:'passed'});await capture('discard-returned');
  await role('combobox','Save fixture mode').selectOption('delayed');await input.fill(`${name} saved`);await role('button','Save').click();await wait(role('button','Saving...'));await role('button','Collection module').click();await wait(prompt);check(await discard.evaluate(el=>el.disabled),'Running save allowed discard');await capture('pending-save-blocks-leave');await stay.click();await wait(role('button','Saved'));await role('button','Collection module').click();await wait(role('heading','My Collection'));check(await prompt.count()===0,'Clean successful save still blocked');await role('button','Deck Builder module').click();await wait(input);check(await input.evaluate(el=>el.value)===`${name} saved`,'Successful save not persisted');cases.push({id:'pending-save-clean-return',status:'passed'});
  await role('combobox','Save fixture mode').selectOption('rejected');await input.fill(`${name} rejected`);await role('button','Save').click();await wait(role('button','Save').and(tab.playwright.locator(':enabled')));await role('button','Collection module').click();await wait(prompt);await stay.click();check(await input.evaluate(el=>el.value)===`${name} rejected`,'Failed save discarded draft');await role('button','Unmount modules').click();await wait(prompt);await discard.click();await role('region','Independent Deck Builder').waitFor({state:'hidden',timeoutMs:15000});const state=await tab.playwright.getByLabel('Host edit state',{exact:true}).evaluate(el=>el.textContent);check(state.includes('0 dirty')&&state.includes('0 save'),'Unmount leaked editing registration');cases.push({id:'failed-save-stay-unmount-cleanup',status:'passed'});await capture('unmounted-clean');
 }catch(error){cases.push({id:'unsaved-host-failure',status:'failed',reason:error.message.replace(/guest_[a-zA-Z0-9_]+/g,'[private fixture]')});try{await capture('failure');}catch{}}
 report.browserErrors=(await tab.dev.logs({levels:['error'],limit:100})).length;report.status=cases.length===3&&cases.every(c=>c.status==='passed')&&report.browserErrors===0?'passed':'needs review';report.counts={passed:cases.filter(c=>c.status==='passed').length,failed:cases.filter(c=>c.status==='failed').length,skipped:0,blocked:Math.max(0,3-cases.length)};report.reportPath=await writeBrowserReport(evidenceDir,report);return report;
}
