import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import { NativeRouteHarness } from './NativeRouteHarness';
import { LocalModuleHarness } from './ModuleHarness';
import { routedHarnessAccess } from './harnessAccess';
const client=new QueryClient({defaultOptions:{queries:{retry:1,refetchOnWindowFocus:false}}});
const root=createRoot(document.getElementById('native-integration-root')!);
const access=routedHarnessAccess('/prepared-host',window.location.pathname);
const router=createBrowserRouter([{path:'*',element:<LocalModuleHarness loadSession={access.loadSession} renderHost={user=><NativeRouteHarness user={user} api={access.api} requestEvidence={access.evidence} isolated />} />}],{basename:access.basename});
root.render(import.meta.env.DEV ? <QueryClientProvider client={client}><RouterProvider router={router} /></QueryClientProvider> : <p>The fixture harness is development-only.</p>);
if(import.meta.hot) import.meta.hot.dispose(()=>{root.unmount();router.dispose();client.clear();});
