import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import { LayoutModeProvider } from '../lib/layout/LayoutModeProvider';
import { LocalModuleHarness } from './ModuleHarness';
import { NativeRouteHarness } from './NativeRouteHarness';
import { NATIVE_HOST_BASE } from './nativeHostRoutes';
import '../styles/appStyles';
import { routedHarnessAccess } from './harnessAccess';
const client = new QueryClient({ defaultOptions: { queries: { retry: 1, refetchOnWindowFocus: false } } });
const root = createRoot(document.getElementById('native-route-root')!);
const access = routedHarnessAccess(NATIVE_HOST_BASE, window.location.pathname);
const router = createBrowserRouter([{path:'*',element:<LocalModuleHarness loadSession={access.loadSession} renderHost={user => <NativeRouteHarness user={user} api={access.api} requestEvidence={access.evidence} />} />}],{basename:access.basename});
root.render(import.meta.env.DEV ? <QueryClientProvider client={client}><LayoutModeProvider><RouterProvider router={router} /></LayoutModeProvider></QueryClientProvider> : <p>The fixture harness is development-only.</p>);
if (import.meta.hot) import.meta.hot.dispose(() => { root.unmount(); router.dispose(); client.clear(); });
